### ISSUE TITLE
BetterDiscord Buttons Disappeared?

### ISSUE THREAD

**Issue by Jepyxl** [JsSucks/BetterDiscordApp#389]
Did reinstall many times, But still gone.

No plugins button and more.

![image](https://user-images.githubusercontent.com/82037272/113713906-0ee49900-9712-11eb-98ca-f6b002c1f167.png)

**Comment by kingcobra8551** [comment]
yeah I'm having this issue as well glad to know its not just me also its continuously trying to load as well I noticed 
![Screenshot (3)](https://user-images.githubusercontent.com/82053907/113756961-0bd0b500-96e0-11eb-9d73-a8aef1508e85.png)

**Comment by Strencher** [comment]
This is the wrong repo. I'm sure the issue has been already solved and should be fixed by a reinstall with the [newest installer](https://github.com/BetterDiscord/Installer/releases/latest)

**Comment by kingcobra8551** [comment]
> This is the wrong repo. I'm sure the issue has been already solved and should be fixed by a reinstall with the [newest installer](https://github.com/BetterDiscord/Installer/releases/latest) i used the latest install and thats what caused this it was working fine before the new version

**Comment by ArdynBlake** [comment]
> This is the wrong repo. I'm sure the issue has been already solved and should be fixed by a reinstall with the [newest installer](https://github.com/BetterDiscord/Installer/releases/latest)

Even with the newest installer I am still having these issues

**Comment by JustPandaPan** [comment]
Bettdiscord just makes my discord crash

**Comment by ArdynBlake** [comment]
> Bettdiscord just makes my discord crash

Honestly, the developers aren’t even being that helpful either, someone posted about this issue the other day on the newer installer and someone closed the case saying they didn’t post it in the right place and didn’t even tell them where the right place to post it was
